name: read-properties-action
description: 读取properties文件并输出为变量
version: 1.0.0
license: MPL-2.0
scripts:
  build: esbuild src/main.js --bundle --platform=node --outfile=bin/main.js
dependencies:
  "@actions/core": ^1.11.1
  properties-file: ^3.5.11
devDependencies:
  esbuild: ^0.24.2
